#!/bin/bash
# 
# Usage: ./download-GEOS-FP DATE
#
# Notes: 
# * DATE format can be any format understood by the bash date command.
# 
set -u
#set -e

URS_COOKIES=$HOME/.urs_cookies

YEAR=$(date -d"$1" +%Y)
MONTH=$(date -d"$1" +%m)
DAY=$(date -d"$1" +%d)

function download_collection() {
    COLLECTION_LONG_NAME=$1
    case $COLLECTION_LONG_NAME in
    *inst3*)
        START_HOUR=0
        FREQ_HOUR=3
        MINUTE=00
        ;;
    *inst1*|*inst_1hr*)
        START_HOUR=0
        FREQ_HOUR=1
        MINUTE=00
        ;;
    *tavg3*)
        START_HOUR=1
        FREQ_HOUR=3
        MINUTE=30
        ;;
    *tavg1*|*tavg_1hr*)
        START_HOUR=0
        FREQ_HOUR=1
        MINUTE=30
        ;;
    *)
        echo "Invalid collection name"
        exit 1
        ;;
    esac
    
    for HOUR in $(seq -w $START_HOUR $FREQ_HOUR 23); do
        FILE_PATH=Y$YEAR/M$MONTH/D${DAY}/GEOS.fp.asm.${COLLECTION_LONG_NAME}.${YEAR}${MONTH}${DAY}_${HOUR}${MINUTE}.V01.nc4
        URL=https://portal.nccs.nasa.gov/datashare/gmao/geos-fp/das/${FILE_PATH}
        printf "Downloading: %s \r" "$URL"
        HTTP_CODE=$(curl --write-out "%{http_code}" --silent -k -n -L -g --url $URL -o $FILE_PATH --create-dirs)
        printf "(status %i) %s   \n" $HTTP_CODE "$URL"
    done
}

download_collection "inst_1hr_ctm_c0720_v72" # "MFXC","MFYC","CX","CY"
download_collection "tavg_1hr_ctm_c0720_v72" # "PS","QV"
download_collection "tavg1_2d_rad_Nx" # "ALBEDO","CLDTOT","LWGNT","SWGDN"
download_collection "tavg1_2d_lnd_Nx" # "FRSNO","GRN","GWETROOT","GWETTOP","LAI","PARDF","PARDR","SNODP","SNOMAS"
download_collection "tavg1_2d_flx_Nx" # "EFLUX","EVAP","FRSEAICE","HFLUX","PBLH","PRECANV","PRECCON","PRECLSC","PRECSNO","PRECTOT","USTAR","Z0M"
download_collection "tavg1_2d_slv_Nx" # "QV2M","SLP","T2M","TO3","TROPPT","TS","U10M","V10M"
download_collection "inst3_3d_asm_Nv" # "PS","QV","T"
download_collection "tavg3_3d_asm_Nv" # "OMEGA","QI","QL","RH","U","V"
download_collection "tavg3_3d_cld_Nv" # "DTRAIN","TAUCLI","TAUCLW"
download_collection "tavg3_3d_mst_Ne" # "CMFMC","PFICU","PFILSAN","PFLCU","PFLLSAN"
download_collection "tavg3_3d_rad_Nv" # "CLOUD"
download_collection "tavg3_3d_mst_Nv" # "DQRCU","DQRLSAN","REEVAPCN","REEVAPLSAN"
download_collection "tavg3_2d_chm_Nx" # "LWI" 
